### ISSUE TITLE
HeadlessUI Switch Component

### ISSUE THREAD

**Issue by ninjha01** [ninjha01/storybook#3]
## Component Description

[Headless UI Switch](https://headlessui.com/react/switch)
<img width="709" alt="image" src="https://user-images.githubusercontent.com/25281692/199371793-70d10cb0-5450-4549-93e3-7b9e44595b1b.png">

Build out a Storybook story of the headless UI Switch component with the following variants. 
This will be a good time to spin up on Storybook, CVA, and HeadlessUI. Open a PR early and tag me if anything isn't clear.

## Task Breakdown

- [x] Create branch and verify that vercel preview deployments work correctly
- [x] Install deps and get storybook running locally
- [x] Look at Button and Button.stories.tsx to create the storybook harness for Switch component
- [x] Verify on local that a new story appears
- [x] Push changes to branch and verify that a new story appears on deployed preview 
- [x] Import HeadlessUI Switch component and style a dark mode and light mode
- [x] Request Code Review

## Style Variants

- [x] Dark Mode
- [x] Light Mode

## Time Estimate
3 hrs

**Comment by digithed** [comment]
1/2 time update: Got toggle component in a story and different styles trigger when selecting radio buttons, however still trying to figure out how to switch states by clicking on the actual toggle button
